version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  redis_data:

networks:
  colyseus-network:
    driver: bridge
