version: '3.8'

services:
  app:
    build: .
    container_name: ci_pet_app
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: ${NODE_ENV}
      NEST_PORT: ${NEST_PORT}
      COLYSEUS_PORT: ${COLYSEUS_PORT}
      ENABLE_REDIS: ${ENABLE_REDIS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MONGO_URI: ${MONGO_URI}
      COLYSEUS_PING_INTERVAL: ${COLYSEUS_PING_INTERVAL}
      COLYSEUS_PING_MAX_RETRIES: ${COLYSEUS_PING_MAX_RETRIES}
      AUTH_ACCESS_SECRET: ${AUTH_ACCESS_SECRET}
      AUTH_REFRESH_SECRET: ${AUTH_REFRESH_SECRET}
      AUTH_ACCESS_TOKEN_EXPIRES_IN: ${AUTH_ACCESS_TOKEN_EXPIRES_IN}
      AUTH_REFRESH_TOKEN_EXPIRES_IN: ${AUTH_REFRESH_TOKEN_EXPIRES_IN}